Add variables
noaa-oar-arl/canopy-app pull request #10
Opened 2022-07-12 19:38 UTC by angehung5

1. input_variables.txt is updated by adding surface roughness length (Z0) and changing to southeast domain
2. domain settings (nlat, nlon) and reading section in canopy_driver.f90 are changed for the updated list

2022-07-12 21:13 UTC, drnimbusrain commented
@angehung5 This looks good, and I am close to merging with develop, but why are the Monin-Obukhov Lengths (MOL) always zero in the new input_variables.txt file?

2022-07-12 21:25 UTC, drnimbusrain requested changes
@angehung5 Please update MOL to have values other than zero.

2022-07-12 21:25 UTC, drnimbusrain commented on canopy_driver.F90
> +           real(rk)    :: mol          !Monin-Obukhov length
@angehung5 All values for MOL are zero here.

2022-07-12 21:40 UTC, angehung5 commented
File updated. Do I need to pull a request again or you can see the change?

2022-07-12 21:42 UTC, zmoon commented
> File updated. Do I need to pull a request again or you can see the change?

We see it. Changes you make in the branch associated with the pull request automatically show up here.

2022-07-13 21:23 UTC, drnimbusrain requested changes
@angehung5 Any idea why the magnitude of values for MOL are so low (typically range from +/- 1 to 200 m)?

2022-07-13 21:28 UTC, zmoon commented
<details><summary>That is consistent with the Stull figure for "typical" conditions</summary>

![image](https://user-images.githubusercontent.com/15079414/178839387-425b834e-7838-4938-97ce-15cddd42d25d.png)

</details>

2022-07-13 22:21 UTC, angehung5 commented
OK, I found the problem. I made a mistake in the heat capacity of air. Now the MOL values should be more reasonable.

2022-07-14 15:05 UTC, drnimbusrain approved these changes

2022-07-14 15:05 UTC, merged